### ISSUE TITLE
Logging exception due to invalid arguments

### ISSUE THREAD

**Issue by murtraja** [Tarteel-io/tarteel-ml#49]
Currently this exception is thrown when downloading files: `python3 download.py`
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "download.py", line 103, in <module>
    download_csv_dataset(args.csv_url, path_to_dataset_csv)
  File "download.py", line 50, in download_csv_dataset
    logging.info("Downloading CSV from ", csv_url, " to ", dataset_csv_path, ".")
Message: 'Downloading CSV from '
Arguments: ('https://tarteel-frontend-static.s3-us-west-2.amazonaws.com/datasets/tarteel_v1.0.csv', ' to ', '.cache/csv/local.csv', '.')
```
It is due to this line:
```logging.info("Downloading CSV from ", csv_url, " to ", dataset_csv_path, ".")```

**Comment by murtraja** [comment]
Fixed by https://github.com/Tarteel-io/tarteel-ml/pull/50
